[package]
name = "wasm_nvim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = {version = "0.8.9", features = ["luajit", "module"]}

[lib]
crate-type = ["cdylib"]
