[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.perf]
command = "nvim"
args = ["-u","NONE","-l","./default_cfg/perf.lua"]
dependencies = ["move","zig_perf"]

[tasks.test]
command = "nvim"
args = ["-u","NONE","-l","./default_cfg/testing.lua"]
dependencies = ["move","zig_test"]

[tasks.ci_test]
command = "./nvim-win64/nvim-win64/bin/nvim"
args = ["-u","NONE","-l","./default_cfg/testing.lua"]
dependencies = ["move","ci_zig_test"]

[tasks.docker_test]
command = "/downloads/nvim-linux64/bin/nvim"
args = ["-u","NONE","-l","./default_cfg/testing.lua"]
dependencies = ["move","docker_zig_test"]

[tasks.docker_zig_test]
command = "/downloads/zig-linux-x86_64-0.11.0/zig"
cwd = "./wasm"
args = ["build-lib","tests.zig","-target","wasm32-wasi", "-dynamic", "-rdynamic"]

[tasks.ci_zig_test]
command = "../zig-windows-x86_64-0.11.0/zig-windows-x86_64-0.11.0/zig"
cwd = "./wasm"
args = ["build-lib","tests.zig","-target","wasm32-wasi", "-dynamic", "-rdynamic"]

[tasks.zig_perf]
command = "zig"
cwd = "./wasm"
args = ["build-lib","perf.zig","-target","wasm32-wasi", "-dynamic", "-rdynamic", "-O", "ReleaseFast"]

[tasks.zig_test]
command = "zig"
cwd = "./wasm"
args = ["build-lib","tests.zig","-target","wasm32-wasi", "-dynamic", "-rdynamic"]

[tasks.zig_wasm]
command = "zig"
cwd = "./wasm"
args = ["build-lib","zig_examp.zig","-target","wasm32-wasi", "-dynamic", "-rdynamic"]

[tasks.nvim]
command = "nvim"
args = ["-u","NONE","-l","./default_cfg/init.lua"]
dependencies = ["move","zig_wasm"]

[tasks.move]
windows_alias = "move_win"
linux_alias = "move_lin"
mac_alias = "move_mac"

[tasks.build]
windows_alias = "build_win"
linux_alias = "build_lin"
mac_alias = "build_lin"

[tasks.docs]
windows_alias = "docs_win"

[tasks.move_win]
script = '''
mkdir lua
copy .\target\release\wasm_nvim.dll .\lua\'''
dependencies = ["build"]

[tasks.move_lin]
script = '''
mkdir -p lua
cp ./target/release/libwasm_nvim.so ./lua/wasm_nvim.so'''
dependencies = ["build"]

[tasks.move_mac]
script = '''
mkdir -p lua
cp ./target/release/libwasm_nvim.dylib ./lua/wasm_nvim.so'''
dependencies = ["build"]

[tasks.build_lin]
script = '''cargo build -r'''

[tasks.build_win]
script = '''
set LUA_INC=%CD%\target\release\build\LuaJIT-2.1.0-beta3\src
set LUA_LIB=%CD%\target\release\build\LuaJIT-2.1.0-beta3\src
set LUA_LIB_NAME=lua51
cargo build -r
'''

[tasks.docs_win]
script = '''
set LUA_INC=%CD%\target\release\build\LuaJIT-2.1.0-beta3\src
set LUA_LIB=%CD%\target\release\build\LuaJIT-2.1.0-beta3\src
set LUA_LIB_NAME=lua51
cargo doc --open
'''
