[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "nvim"
args = ["-u","NONE","-l","./default_cfg/testing.lua"]
dependencies = ["move","zig_test"]

[tasks.zig_test]
command = "zig"
cwd = "./wasm"
args = ["build-lib","tests.zig","-target","wasm32-wasi", "-dynamic", "-rdynamic"]

[tasks.zig_wasm]
command = "zig"
cwd = "./wasm"
args = ["build-lib","zig_examp.zig","-target","wasm32-wasi", "-dynamic", "-rdynamic"]

[tasks.nvim]
command = "nvim"
args = ["-u","NONE","-l","./default_cfg/init.lua"]
dependencies = ["move","zig_wasm"]

[tasks.move]
windows_alias = "move_win"

[tasks.build]
windows_alias = "build_win"

[tasks.docs]
windows_alias = "docs_win"

[tasks.move_win]
script-runner = "@shell"
script = '''copy .\target\release\wasm_nvim.dll .\'''
dependencies = ["build"]

[tasks.build_win]
script-runner = "powershell"
script = '''
set LUA_INC=%CD%\target\release\build\LuaJIT-2.1.0-beta3\src
set LUA_LIB=%CD%\target\release\build\LuaJIT-2.1.0-beta3\src
set LUA_LIB_NAME=lua51
cargo build -r
'''

[tasks.docs_win]
script-runner = "powershell"
script = '''
set LUA_INC=%CD%\target\release\build\LuaJIT-2.1.0-beta3\src
set LUA_LIB=%CD%\target\release\build\LuaJIT-2.1.0-beta3\src
set LUA_LIB_NAME=lua51
cargo doc --open
'''
