[package]
name = "wasm_nvim"
version = "0.0.2"
edition = "2021"
authors = ["Brian Orwe <brian.orwe@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
mlua = {version = "0.11.2", features = ["luajit", "module"]}
anyhow = "1.0"
lazy_static = "1.4.0"
libc = "0.2.147"
serde = {version = "1.0.171",  features = ["derive"]}
serde_json = "1.0.103"
wasmtime = {version = "35.0.0", features = ["std", "default"]}
wasmtime-wasi = "35.0.0"

[lib]
crate-type = ["cdylib"]

