name: Push Build

on: push

jobs:
  build_and_test:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
          - {
              name: "Linux Build & Test",
              os: ubuntu-latest
            }
          - {
              name: "Microsoft Windows Build & Test",
              os: windows-latest
            }
          - {
              name: "MacOs Build & Test",
              os: macos-latest
            }
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Cargo make
        run: |
          cargo install cargo-make

      - name: Download files Linux
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          wget "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
          tar -xzf nvim-linux64.tar.gz
          wget "https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz"
          tar -xf zig-linux-x86_64-0.11.0.tar.xz

      - name: Download files MacOs
        if: matrix.config.os == 'macos-latest'
        run: |
          wget "https://github.com/neovim/neovim/releases/download/v0.9.1/nvim-macos.tar.gz"
          tar -xzf nvim-macos.tar.gz
          wget "https://ziglang.org/download/0.11.0/zig-macos-x86_64-0.11.0.tar.xz"
          tar -xf zig-macos-x86_64-0.11.0.tar.xz

      - name: Download files Windows
        if: matrix.config.os == 'windows-latest'
        run: |
          Invoke-WebRequest "https://github.com/neovim/neovim/releases/download/stable/nvim-win64.zip" -OutFile .\nvim-win64.zip
          Expand-Archive nvim-win64.zip 
          Invoke-WebRequest "https://ziglang.org/download/0.11.0/zig-windows-x86_64-0.11.0.zip" -OutFile .\zig-windows-x86_64-0.11.0.zip
          Expand-Archive zig-windows-x86_64-0.11.0.zip

      - name: Test For Linux
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          export PATH=$PWD/nvim-linux64/bin/:$PATH
          export PATH=$PWD/zig-linux-x86_64-0.11.0/:$PATH
          cargo make test

      - name: Test For MacOs
        if: matrix.config.os == 'macos-latest'
        run: |
          export PATH=$PWD/nvim-macos/bin/:$PATH
          export PATH=$PWD/zig-macos-x86_64-0.11.0/:$PATH
          cargo make test

      - name: Test For Windows
        if: matrix.config.os == 'windows-latest'
        shell: pwsh
        run: |
          $env:CD = Get-Location
          $env:PATH=$env:CD+'/nvim-win64/bin/;'+$env:PATH
          $env:PATH=$env:CD+'/zig-windows-x86_64-0.11.0/zig-windows-x86_64-0.11.0/;'+$env:PATH
          cargo make ci_test

      - name: Zip file Unix
        run: |
          zip ./lua/wasm_nvim.so ./wasm_nvim_$${{matrix.config.os}}.zip

