name: Push Build

on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare Env Build And Test
        run: |
          cargo install cargo-make
          sudo apt-get update
          wget "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
          tar -xzf nvim-linux64.tar.gz
          export PATH=$PWD/nvim-linux64/bin/:$PATH
          wget "https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz"
          tar -xf zig-linux-x86_64-0.11.0.tar.xz
          export PATH=$PWD/zig-linux-x86_64-0.11.0/:$PATH
          cargo make test

