name: Push Build

on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare Env Build And Test
        run: |
          cargo install cargo-make
          wget "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
          tar -xzf nvim-linux64.tar.gz
          export PATH=$PWD/nvim-linux64/bin/:$PATH
          wget "https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz"
          tar -xf zig-linux-x86_64-0.11.0.tar.xz
          export PATH=$PWD/zig-linux-x86_64-0.11.0/:$PATH
          cargo make test

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare Env Build And Test
        shell: pwsh
        run: |
          $env:CD = Get-Location
          cargo install cargo-make
          Invoke-WebRequest "https://github.com/neovim/neovim/releases/download/stable/nvim-win64.zip" -OutFile .\nvim-win64.zip
          Expand-Archive nvim-win64.zip 
          $env:PATH=$env:CD+'/nvim-win64/bin/;'+$env:PATH
          Invoke-WebRequest "https://ziglang.org/download/0.11.0/zig-windows-x86_64-0.11.0.zip" -OutFile .\zig-windows-x86_64-0.11.0.zip
          Expand-Archive zig-windows-x86_64-0.11.0.zip
          $env:PATH=$env:CD+'/zig-windows-x86_64-0.11.0/;'+$env:PATH
          cargo make test
